"""CSV writer that produces the fixed legacy 3-block benchmark format.

Metalogalva already consumes CSV files generated by ``ocr6.py`` (legacy
script). Benchmark tooling must continue to produce byte-identical output
for the same extraction so existing downstream tooling keeps working.
The unit tests in :mod:`tests.unit.test_csv_writer` enforce this with a
byte-by-byte regression fixture.

Format summary:

- Encoding: ``utf-8-sig`` (UTF-8 with BOM).
- Delimiter: ``;``.
- Three blocks separated by an empty line: ``### CABEÇALHO``,
  ``### TABELA DE PRODUÇÃO``, ``### RODAPÉ``.
"""
from __future__ import annotations

import csv
from pathlib import Path

from app.pipeline.inference.schemas import KanbanExtraction

ExtractionItem = tuple[str, KanbanExtraction]
"""Pair of (filename, extraction) — one Kanban sheet."""

_HEADER_BLOCK_HEADERS = ["FICHEIRO", "DATA", "OPERADOR", "N_OPERADOR", "SETOR_MAQUINA"]

_TABLE_BLOCK_HEADERS = [
    "FICHEIRO",
    "DATA",
    "OPERADOR",
    "PRI",
    "CLIENTE",
    "OV",
    "OF",
    "MODELO",
    "QTD",
    "COMP_MM",
    "LARG_MM",
    "LOTE",
    "CONI",
    "ESP",
    "LBASE",
    "LTOPO",
]

_FOOTER_BLOCK_HEADERS = [
    "FICHEIRO",
    "DATA",
    "OPERADOR",
    "COLUNAS_PRODUZIDAS",
    "HORAS_TRABALHADAS",
]


def write_csv(output_path: Path, items: list[ExtractionItem]) -> None:
    """Write ``items`` to ``output_path`` in the legacy 3-block format."""
    with output_path.open("w", newline="", encoding="utf-8-sig") as fh:
        writer = csv.writer(fh, delimiter=";")

        writer.writerow(["### CABEÇALHO"])
        writer.writerow(_HEADER_BLOCK_HEADERS)
        for filename, extraction in items:
            h = extraction.header
            writer.writerow([filename, h.data, h.operador, h.n_operador, h.setor_maquina])
        writer.writerow([])

        writer.writerow(["### TABELA DE PRODUÇÃO"])
        writer.writerow(_TABLE_BLOCK_HEADERS)
        for filename, extraction in items:
            h = extraction.header
            for row in extraction.rows:
                writer.writerow(
                    [
                        filename,
                        h.data,
                        h.operador,
                        row.pri,
                        row.cliente,
                        row.ov,
                        row.of,
                        row.modelo,
                        row.qtd,
                        row.comp_mm,
                        row.larg_mm,
                        row.lote,
                        row.coni,
                        row.esp,
                        row.lbase,
                        row.ltopo,
                    ]
                )
        writer.writerow([])

        writer.writerow(["### RODAPÉ"])
        writer.writerow(_FOOTER_BLOCK_HEADERS)
        for filename, extraction in items:
            h = extraction.header
            ft = extraction.footer
            writer.writerow(
                [filename, h.data, h.operador, ft.colunas_produzidas, ft.horas_trabalhadas]
            )
